---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# svyfosr

<!-- badges: start -->
<!-- badges: end -->

The goal of svyfosr is to perform survey-weighted function on scalar regression. 

## Installation

You can install the development version of svyfosr from [GitHub](https://github.com/) with:

``` r
# install.packages("pak")
pak::pak("jhuwit/svyfosr")
```

## Example

We load some simulated survey data. 

```{r example}
library(svyfosr)
library(ggplot2)
data(sample_df)

sample_df %>% 
  dplyr::glimpse()

Y_df = sample_df$Y %>% 
  tibble::as_tibble() %>% 
  dplyr::mutate(id = dplyr::row_number()) %>% 
  tidyr::pivot_longer(cols = -id) %>% 
  dplyr::mutate(l = as.numeric(sub(".*Y", "", name)))

Y_df %>% 
  dplyr::filter(id %in% 1:10) %>% 
  ggplot(aes(x = l, y = value, group = factor(id), color = factor(id))) +
  geom_line(alpha = 0.25) + 
  geom_smooth(se = FALSE) + 
  theme_classic(paper = "lightgrey") +
  scale_color_viridis_d(option = "D") +
  theme(legend.position = "none",
        title = element_text(size = 14)) +
  theme_sub_axis(text = element_text(size = 12),
                 title = element_text(size = 14))  +
  labs(x = "Functional Domain", y = "Y", title = "Smoothed Outcomes for 10 Random Subjects")
```
We fit a survey-weighted FoSR model using balanced repeated replication (BRR) to estimate standard errors.

```{r}
model_fit = svyfosr::svyfui(Y ~ X,
                            data = sample_df, 
                            weights = weight,
                            family = gaussian(),
                            boot_type = "BRR",
                            num_boots = 100,
                            parallel = TRUE,
                            n_cores = 6, 
                            seed = 2213)

plot(model_fit)
```




